config/routes.rb
Rails.application.routes.draw do
  #ホーム画面
  root 'home#index' 

  #ログイン管理
  devise_for :users # /users/sign_in, /users/sign_out, /users/sign_up

  #Posts関連
  resources :posts, except: [:show, :edit, :update, :destroy]
  get '/:username/items/:link', to: 'posts#show'
  get '/:username/items/:link/edit', to: 'posts#edit'
  patch '/:username/items/:link', to: 'posts#update'
  delete '/:username/items/:link', to: 'posts#destroy'
  get 'articles', to: 'posts#articles'
  get 'questions', to: 'posts#questions'
  get 'drafts', to: 'posts#drafts'

  #コメントといいね
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :comments do
    resources :likes, only: [:create, :destroy]
  end

  #設定
  get 'settings/account', to: 'settings#account'
  patch 'settings/account', to: 'settings#update_account', as: 'update_account_settings'

  get 'settings/profile', to: 'settings#profile'
  patch 'settings/profile', to: 'settings#update_profile', as: 'update_profile_settings'

  get 'settings/notification', to: 'settings#notification'
  patch 'settings/notification', to: 'settings#update_notification', as: 'update_notification_settings'

  #mypage
  get '/:username/mypage/profile', to: 'mypage#profile'

  get '/:username/mypage/articles', to: 'mypage#articles'
  get '/:username/mypage/comments', to: 'mypage#comments'

  get '/:username/mypage/questions', to: 'mypage#questions'
  get '/:username/mypage/answers', to: 'mypage#answers'

  get '/:username/mypage/likes/articles', to: 'mypage#likes_articles'
  get '/:username/mypage/likes/comments', to: 'mypage#likes_comments'
  get '/:username/mypage/likes/questions', to: 'mypage#likes_questions'
  get '/:username/mypage/likes/answers', to: 'mypage#likes_answers'

  #いいねのカウント
  get '/likes/count', to: 'likes#count'

  #テスト
  get "hello", to: "hello#index"

end

app/controllers/settings_controller.rb
# app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user
  
    #アカウント設定
    def account
    end
    
    def update_account
        if params[:user][:icon_photo]
          uploaded_file = params[:user][:icon_photo]
          icon_photo_name = upload_to_s3(uploaded_file)
          params[:user][:icon_photo_name] = icon_photo_name if icon_photo_name
        end
        
        if @user.update(user_params)
          redirect_to settings_account_path, notice: 'Account updated successfully.'
        else
          render :account, status: :unprocessable_entity
        end
    end
      
    def upload_to_s3(uploaded_file)
        s3 = Aws::S3::Resource.new
        obj_key = "user-icon/#{uploaded_file.original_filename}"
        obj = s3.bucket('my-unique-bucket-name-shiroatohiro').object(obj_key)
        obj.upload_file(uploaded_file.path)
        return obj.public_url 
    end

    #プロフィール設定
    def profile
        @profile = @user.profile || @user.build_profile
    end

    def update_profile
      @profile = @user.profile || @user.build_profile
      if @profile.update(profile_params)
        redirect_to settings_profile_path, notice: 'Profile updated successfully.'
      else
        render :profile, status: :unprocessable_entity
      end
    end
  
    #通知設定
    def notification
      @notification = @user.notification || @user.build_notification
    end

    def update_notification
      @notification = @user.notification || @user.build_notification
      if @notification.update(notification_params)
        redirect_to settings_notification_path, notice: 'Notification settings updated successfully.'
      else
        render :notification, status: :unprocessable_entity
      end
    end
  
    private
  
    def set_user
      @user = current_user
    end
  
    def user_params
      params.require(:user).permit(:username, :email, :icon_photo_name, :language)
    end
  
    def profile_params
      params.require(:profile).permit(:name, :public_email, :github, :website, :organization, :location, :introduction, :sns1, :sns2, :sns3, :sns4, :sns5, :sns6)
    end
  
    def notification_params
      params.require(:notification).permit(:email1, :email2, :email3, :email4, :email5, :email6, :like, :comment, :answer)
    end
end
  

app/views/settings/account.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>

<%= render 'shared/header' %>
<%= render 'shared/header_settings' %>

<div class="container mx-auto my-8 p-8 bg-white shadow-md rounded">
    <div class="mb-6">
        <h1 class="text-3xl font-semibold mb-6">アカウント設定</h1>
    </div>

    <%= form_with(model: @user, url: update_account_settings_path, method: :patch, local: true, class: "space-y-4") do |form| %>
        
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
              <strong class="font-bold">Oops!</strong>
              <span class="block sm:inline"><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</span>
              <ul class="list-disc list-inside mt-2">
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      
        <div class="field">
          <%= form.label :username, class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_field :username, class: "mt-2 block w-full border-4 border-gray-300 shadow-sm rounded-md" %>
        </div>
      
        <div class="field">
          <%= form.label :email, class: "block text-sm font-medium text-gray-700" %>
          <%= form.email_field :email, class: "mt-2 block w-full border-4 border-gray-300 shadow-sm rounded-md" %>
        </div>

        <div class="field">
            <%= form.label :language, class: "block text-sm font-medium text-gray-700" %>
            <%= form.select :language, [['Japanese', 'Japanese'], ['English', 'English']], {}, class: "mt-2 block w-full border-4 border-gray-300 shadow-sm rounded-md" %>
        </div>

        <div class="field">
            <% if @user.icon_photo_name == "default.png" %>
                <%= image_tag "default.png", alt: "Default icon", class: "h-24 w-24 rounded-full mx-auto" %>
            <% else %>
                <%= image_tag @user.generate_presigned_url('my-unique-bucket-name-shiroatohiro', @user.icon_photo_name), alt: "User icon", class: "h-24 w-24 rounded-full mx-auto" %>
            <% end %>
        </div>
        
        <div class="field mb-6">
            <%= form.label :icon_photo, class: "block text-sm font-medium text-gray-700" %>
            <%= form.file_field :icon_photo, class: "mt-2 block w-full border-4 border-gray-300 shadow-sm rounded-md" %>
        </div>

        <div class="actions flex justify-center mt-6">
          <%= form.submit "保存", class: "px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 focus:outline-none focus:ring" %>
        </div>
    <% end %>
</div>

</body>

app/views/settings/notification.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>

<%= render 'shared/header' %>
<%= render 'shared/header_settings' %>

<div class="container mx-auto my-8 p-8 bg-white shadow-md rounded">
  <h2 class="text-3xl font-semibold mb-6">通知設定</h2>

  <%= form_with(model: @notification, url: update_notification_settings_path, method: :patch, local: true, class: "space-y-4") do |form| %>
    
    <div id="error_explanation">
      <% if @notification.errors.any? %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold">Oops!</strong>
          <span class="block sm:inline"><%= pluralize(@notification.errors.count, "error") %> prohibited this post from being saved:</span>
          <ul class="list-disc list-inside mt-2">
            <% @notification.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    
    <% (1..6).each do |i| %>
      <div class="field">
        <%= form.label "email#{i}", class: "block text-sm font-medium text-gray-700" %>
        <%= form.text_field "email#{i}", class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>
      </div>
    <% end %>

    <div class="flex items-center mb-4">
      <%= form.label :like, class: "mr-2 text-sm font-medium text-gray-700" %>
      <%= form.check_box :like, class: "border-4 border-gray-300 rounded text-blue-600 shadow-sm" %>
    </div>

    <div class="flex items-center mb-4">
      <%= form.label :comment, class: "mr-2 text-sm font-medium text-gray-700" %>
      <%= form.check_box :comment, class: "border-4 border-gray-300 rounded text-blue-600 shadow-sm" %>
    </div>

    <!--いらない-->
    <div class="flex items-center mb-4 hidden">
      <%= form.label :answer, class: "mr-2 text-sm font-medium text-gray-700" %>
      <%= form.check_box :answer, class: "border-4 border-gray-300 rounded text-blue-600 shadow-sm" %>
    </div>

    <div class="flex justify-end mt-6">
      <%= form.submit "保存", class: "px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 focus:outline-none focus:ring" %>
    </div>
  <% end %>
</div>

</body>

app/views/settings/profile.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>

<%= render 'shared/header' %>
<%= render 'shared/header_settings' %>

<div class="container mx-auto my-8 p-8 bg-white shadow-md rounded">
  <h2 class="text-3xl font-semibold mb-6">プロフィール設定</h2>

  <%= form_with(model: @profile, url: update_profile_settings_path, method: :patch, local: true, class: "space-y-4") do |form| %>
    
    <div id="error_explanation">
      <% if @profile.errors.any? %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold">Oops!</strong>
          <span class="block sm:inline"><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</span>
          <ul class="list-disc list-inside mt-2">
            <% @profile.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    
    <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :name, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>

    <%= form.label :public_email, class: "block text-sm font-medium text-gray-700" %>
    <%= form.email_field :public_email, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>

    <%= form.label :github, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :github, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>

    <%= form.label :website, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :website, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>

    <%= form.label :organization, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :organization, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>

    <%= form.label :location, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :location, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>

    <%= form.label :introduction, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :introduction, class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm", rows: 4 %>

    <% (1..6).each do |i| %>
      <%= form.label "sns#{i}", "SNS #{i}", class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field "sns#{i}", class: "mt-1 block w-full border-4 border-gray-300 rounded-md shadow-sm" %>
    <% end %>

    <div class="flex justify-end mt-6">
      <%= form.submit "保存", class: "px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 focus:outline-none focus:ring" %>
    </div>
  <% end %>
</div>

</body>