config/routes.rb
Rails.application.routes.draw do
  #ホーム画面
  root 'home#index' 

  #ログイン管理
  devise_for :users # /users/sign_in, /users/sign_out, /users/sign_up

  #Posts関連
  resources :posts, except: [:show, :edit, :update, :destroy]
  get '/:username/items/:link', to: 'posts#show'
  get '/:username/items/:link/edit', to: 'posts#edit'
  patch '/:username/items/:link', to: 'posts#update'
  delete '/:username/items/:link', to: 'posts#destroy'
  get 'articles', to: 'posts#articles'
  get 'questions', to: 'posts#questions'
  get 'drafts', to: 'posts#drafts'

  #コメントといいね
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :comments do
    resources :likes, only: [:create, :destroy]
  end

  #設定
  get 'settings/account', to: 'settings#account'
  patch 'settings/account', to: 'settings#update_account', as: 'update_account_settings'

  get 'settings/profile', to: 'settings#profile'
  patch 'settings/profile', to: 'settings#update_profile', as: 'update_profile_settings'

  get 'settings/notification', to: 'settings#notification'
  patch 'settings/notification', to: 'settings#update_notification', as: 'update_notification_settings'

  #mypage
  get '/:username/mypage/profile', to: 'mypage#profile'

  get '/:username/mypage/articles', to: 'mypage#articles'
  get '/:username/mypage/comments', to: 'mypage#comments'

  get '/:username/mypage/questions', to: 'mypage#questions'
  get '/:username/mypage/answers', to: 'mypage#answers'

  get '/:username/mypage/likes/articles', to: 'mypage#likes_articles'
  get '/:username/mypage/likes/comments', to: 'mypage#likes_comments'
  get '/:username/mypage/likes/questions', to: 'mypage#likes_questions'
  get '/:username/mypage/likes/answers', to: 'mypage#likes_answers'

  #いいねのカウント
  get '/likes/count', to: 'likes#count'

  #テスト
  get "hello", to: "hello#index"

end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, as: :likeable, dependent: :destroy
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
  
    validates :title, presence: true
    validates :content, presence: true
    validates :post_type, inclusion: { in: ['article', 'question'] }
    validates :link, presence: true
    validates :draft, inclusion: { in: [true, false] }

    before_validation :set_link, on: :create

    # 並び替えのスコープを定義する
    scope :filter_sort, -> (sort_param) {
      case sort_param
      when 'created_at_desc'
        order(created_at: :desc)
      when 'updated_at_desc'
        order(updated_at: :desc)
      when 'likes_count_desc'
        left_joins(:likes).group(:id).order('COUNT(likes.id) DESC')
      when 'comments_count_desc'
        left_joins(:comments).group(:id).order('COUNT(comments.id) DESC')
      else
        order(created_at: :desc)
      end
    }

    def self.ransackable_attributes(auth_object = nil)
      %w[title content]
    end
  
    # どの関連を検索可能にするかを定義
    def self.ransackable_associations(auth_object = nil)
      %w[tags user]
    end

    private

    def set_link
      if self.link.blank?
        self.link = "#{SecureRandom.uuid}"
        logger.debug("Link set to #{self.link}")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :drafts] 
  before_action :set_post, only: [:edit, :update, :destroy, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  #記事作成
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_names = params[:post][:tags].split(',').map(&:strip).uniq
    tags = tag_names.map do |name|
      Tag.find_or_create_by(name: name)
    end
    @post.tags = tags  
  
    if params[:commit] == 'Save Draft' || params[:commit] == 'Save'
      @post.draft = true
    else
      @post.draft = false
    end
  
    if @post.save
      if params[:commit] == 'Save'
        redirect_to "/#{@post.user.username}/items/#{@post.link}/edit", allow_other_host: true, notice: "Saved successfully."
      else
        redirect_to "/#{@post.user.username}/items/#{@post.link}/", allow_other_host: true, notice: 'Article created successfully.'
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  #記事の編集
  def edit
    @post = Post.includes(:user).find_by!(link: params[:link])
    if @post.user == current_user
      render :edit
    else
      redirect_to root_path, alert: "You are not allowed to access this page."
    end
  end
  
  def update
    @post = Post.includes(:user).find_by!(link: params[:link])
    
    if params[:commit] == 'Save Draft' || params[:commit] == 'Save'
      @post.draft = true
    else
      @post.draft = false
    end

    if @post.update(post_params)
      if params[:commit] == 'Save'
        redirect_to "/#{params[:username]}/items/#{params[:link]}/edit", notice: "Saved successfully."
      else
        redirect_to "/#{params[:username]}/items/#{params[:link]}/", notice: "Article updated successfully."
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  #記事の削除
  def destroy
    if @post.destroy
      if @post.post_type == "article"
        redirect_to "/articles/", notice: "Article was successfully deleted."
      elsif @post.post_type == "question"
        redirect_to "/questions/", notice: "Article was successfully deleted."
      end
    else
      redirect_to "/#{params[:username]}/items/#{params[:link]}/", alert: "Article could not be deleted."
    end
  end

  #記事の1ページ
  def show
    @post = Post.includes(:user, :comments, :likes).find_by!(link: params[:link])
    @comments = @post.comments # 記事に紐づくコメント
    @likes_count = @post.likes.count # いいねの数
    @likes_count_for_comments = Comment.joins(:likes).where(post_id: @post.id).group(:id).count
  
    if @post.draft && @post.user != current_user
      redirect_to root_path, alert: "You are not allowed to view this draft."
    end
  end

  #記事の一覧を表示する
  def articles
    @q = Post.ransack(params[:q]) 
    @posts = posts('article', false)
  end

  def questions
    @q = Post.ransack(params[:q]) 
    @posts = posts('question', false)
  end

  def drafts
    @q = Post.ransack(params[:q]) 
    @posts = posts(['article', 'question'], true).where(user: current_user)
  end

  def posts(post_type, draft)
    search_params = params[:q] || {}
    sort_option = search_params[:s] || 'created_at_desc'
    posts_scope = Post.includes(:user, :tags).where(post_type: post_type, draft: draft)
    if search_params[:title_or_content_or_tags_name_or_user_username_cont_all].present?
      keywords = search_params[:title_or_content_or_tags_name_or_user_username_cont_all].split(' ')
      keywords.each do |keyword|
        posts_scope = Post.where(id: posts_scope.select(:id)).eager_load(:tags).ransack({
          title_or_content_or_tags_name_or_user_username_cont_any: keyword
        }).result(distinct: true)
      end
    else
      logger.debug "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
    end
    posts_with_all_tags = Post.where(id: posts_scope.select(:id)).eager_load(:tags)
    posts_with_all_tags.filter_sort(sort_option).page(params[:page]).per(6)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :post_type)
  end

  def set_post
    @post = Post.includes(:user).find_by!(link: params[:link])
  end

  def authorize_user!
    redirect_to root_path, alert: "You are not allowed to perform this action." unless @post.user == current_user
  end
end

app/views/posts/articles.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
<%= render 'shared/header' %>
<%= render 'shared/content_posts', edit_path: false %>

</body>

app/views/posts/drafts.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
<%= render 'shared/header' %>
<%= render 'shared/content_posts', edit_path: true %>

</body>

app/views/posts/edit.html.erb
<head>
  <meta charset="UTF-8">
  <title>記事作成フォーム</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/dompurify/dist/purify.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'shared/header' %>
<%= render 'shared/create_update_article', edit: true %>

</body>

app/views/posts/new.html.erb
<head>
  <meta charset="UTF-8">
  <title>記事作成フォーム</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/dompurify/dist/purify.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


</head>

<body>
<%= render 'shared/header' %>
<%= render 'shared/create_update_article', edit: false %>

</body>

app/views/posts/questions.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
<%= render 'shared/header' %>
<%= render 'shared/content_posts', edit_path: false %>

</body>

app/views/posts/show.html.erb
<head>
  <!-- Tailwind CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <script type="text/javascript" id="MathJax-script" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.1.2/es5/tex-mml-chtml.min.js"></script>

</head>

<body class="bg-gray-100">

<%= render 'shared/header' %>

<div class="container mx-auto p-6">
  <div class="bg-white shadow-lg rounded-lg overflow-hidden p-6">
    <h1 class="text-2xl font-bold text-gray-800 mb-2"><%= @post.title %></h1>
    <p class="text-md text-gray-600"><strong>Type:</strong> <%= @post.post_type %></p>
    <p class="text-md text-gray-600"><strong>Author:</strong> <%= @post.user.username %></p>
    <p class="text-md text-gray-600"><strong>Created at:</strong> <%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
    <p class="text-md text-gray-600"><strong>Updated at:</strong> <%= @post.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
    <div class="mt-4">
      <strong>Content:</strong>
      <div class="prose max-w-none mt-2"><div class='reset'><%= raw @post.content %></div></div>
    </div>
  </div>
</div>


<% if current_user == @post.user %>
  <div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden p-6">
      <!-- ... その他の投稿内容 ... -->
      <div class="mt-4 flex justify-end space-x-2">
        <%= link_to "/#{@post.user.username}/items/#{@post.link}/edit", class: "inline-flex items-center px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" do %>
          編集
        <% end %>
        <%= link_to "/#{@post.user.username}/items/#{@post.link}", method: :delete, data: { confirm: "この記事を削除してもよろしいですか？" }, class: "inline-flex items-center px-4 py-2 bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" do %>
          削除
        <% end %>
      </div>
    </div>
  </div>
<% end %>


<% if @post.draft == false %>
  <!-- いいねボタン -->
  <div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg p-6 mb-4 flex items-center justify-between">
      <!-- いいねの数 -->
      <div class="text-gray-700 font-bold">いいねの数: <%= @likes_count %></div>
      <!-- いいね/いいね解除ボタン -->
        <% if current_user %>
          <% like = current_user.likes.find_by(likeable: @post) %>
          <% if like %>
            <%= link_to post_like_path(@post, like), method: :delete, class: "bg-white h-12 w-12 rounded-full overflow-hidden relative", data: { confirm: "いいねを解除しますか？" } do %>
              <%= image_tag "heart.png", alt: "いいね解除", class: "absolute inset-0 h-full w-full" %>
              <div class="absolute inset-0 bg-gray-500 opacity-0 hover:opacity-30"></div>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(@post), method: :post, class: "bg-white h-12 w-12 rounded-full overflow-hidden relative" do %>
              <%= image_tag "heart_frame.png", alt: "いいね", class: "absolute inset-0 h-full w-full" %>
              <div class="absolute inset-0 bg-gray-500 opacity-0 hover:opacity-30"></div>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </div>

  <!-- コメント -->
  <div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg p-6 mb-4">
        <div class="mb-2">
          <span class="text-gray-700 font-bold">コメント ( <%= @comments.size %> )</span>
        </div>
        <div class='mb-8'>
          <% @comments.each do |comment| %>
            <div class="bg-white border-t border-gray-200 rounded-lg p-6 mb-4 flex items-center justify-between">
              <div class="">
                <p class="text-gray-600"><%= comment.body %></p>
                <p class="text-xs text-gray-500">投稿者: <%= comment.user.username %> | 投稿日: <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
                <p class="text-xs text-gray-500">いいね数: <%= @likes_count_for_comments[comment.id] || 0 %></p>
              </div>
              <% if current_user %>
                <% like = current_user.likes.find_by(likeable: comment) %>
                <% if like %>
                  <%= link_to comment_like_path(comment, like), method: :delete, class: "bg-white h-12 w-12 rounded-full overflow-hidden relative", data: { confirm: "いいねを解除しますか？" } do %>
                    <%= image_tag "heart.png", alt: "いいね解除", class: "absolute inset-0 h-full w-full" %>
                    <div class="absolute inset-0 bg-gray-500 opacity-0 hover:opacity-30"></div>
                  <% end %>
                <% else %>
                  <%= link_to comment_likes_path(comment), method: :post, class: "bg-white h-12 w-12 rounded-full overflow-hidden relative" do %>
                    <%= image_tag "heart_frame.png", alt: "いいね", class: "absolute inset-0 h-full w-full" %>
                    <div class="absolute inset-0 bg-gray-500 opacity-0 hover:opacity-30"></div>
                  <% end %>
                <% end %>
              <% end %>
              <% if current_user == comment.user || current_user == @post.user %>
                <%= link_to 'コメントを削除', comment_path(comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md text-sm font-medium" %>
              <% end %>
            </div>
          <% end %>
        </div>
      <!-- コメントフォーム -->
      <%= form_with(model: [ @post, Comment.new ], local: true) do |form| %>
        <div class="mb-3">
          <%= form.text_area :body, rows: 4, placeholder: "コメントを追加...", class: "border-4 border-gray-300 form-input w-full rounded" %>
        </div>
        <%= form.submit "コメント投稿", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-2" %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg p-6 mb-4">
      <div>これは下書きです。</div>
    </div>
  </div>
<% end %>




</body>